### ISSUE TITLE
Error in installing using Docker

### ISSUE THREAD

**Issue by vinodk333** [alfredfrancis/ai-chatbot-framework#120]
Getting below error while installing (docker-compose build).  I installed node-sass using npm install node-sass and still issue persists.  Please help.

Step 7/12 : RUN $(npm bin)/ng build --prod --build-optimizer
 ---> Running in 7fc8689fd4c8
Date: 2018-12-10T14:05:57.449Z
Hash: 5f2631cfd21097a2c42c
Time: 3665ms
chunk {0}  (styles) [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in ./src/styles.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/ng-app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (/ng-app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /ng-app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
ERROR in Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/ng-app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (/ng-app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /ng-app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
ERROR in ./src/styles.scss
Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/ng-app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (/ng-app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /ng-app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at runLoaders (/ng-app/node_modules/webpack/lib/NormalModule.js:195:19)
    at /ng-app/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /ng-app/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/ng-app/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /ng-app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/ng-app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /ng-app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/ng-app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/ng-app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/ng-app/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/ng-app/node_modules/webpack/lib/NormalModule.js:275:15)
ERROR: Service 'iky_gateway' failed to build: The command '/bin/sh -c $(npm bin)/ng build --prod --build-optimizer' returned a non-zero code: 1

**Comment by vinodk333** [comment]
Can someone help please?

**Comment by alfredfrancis** [comment]
AThis is not supposed to happen. Did you make any changes in the angular part? package.json maybe?

**Comment by ahlemdaoud** [comment]
same error here
