### ISSUE TITLE
Install local version

### ISSUE THREAD

**Issue by waitwathuh** [alfredfrancis/ai-chatbot-framework#13]
Good day. I'm having trouble installing your app on Ubuntu. 

It's a clean Ubuntu VM with Python installed. I'm using the steps on your main page under "without docker". I have installed the requirements and run the "setup.py" script. However, when I run the "run.py" script I get the following error in the console: 

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import app
  File "/tmp/ai-chatbot-framework-master/app/__init__.py", line 21, in <module>
    from app.core.controllers import core as core
  File "/tmp/ai-chatbot-framework-master/app/core/controllers.py", line 6, in <module>
    from app.core.intentClassifier import IntentClassifier
  File "/tmp/ai-chatbot-framework-master/app/core/intentClassifier.py", line 1, in <module>
    import app.core.sentenceClassifer as sentenceClassifer
  File "/tmp/ai-chatbot-framework-master/app/core/sentenceClassifer.py", line 4, in <module>
    from sklearn import preprocessing
ImportError: No module named sklearn
```

Could you please provide a step-by-step noobs guide to installing this on Linux please?

**Comment by alfredfrancis** [comment]
go inside project directory and do `
`pip install -r requirements.txt
This will install all required packages including sklearn

**Comment by waitwathuh** [comment]
I did that already. The next step listed is to run the "run.py" script. That is when I get the following error messge: 

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import app
  File "/tmp/ai-chatbot-framework-master/app/__init__.py", line 21, in <module>
    from app.core.controllers import core as core
  File "/tmp/ai-chatbot-framework-master/app/core/controllers.py", line 6, in <module>
    from app.core.intentClassifier import IntentClassifier
  File "/tmp/ai-chatbot-framework-master/app/core/intentClassifier.py", line 1, in <module>
    import app.core.sentenceClassifer as sentenceClassifer
  File "/tmp/ai-chatbot-framework-master/app/core/sentenceClassifer.py", line 4, in <module>
    from sklearn import preprocessing
ImportError: No module named sklearn
```

**Comment by alfredfrancis** [comment]
When installing on Ubuntu Linux you have to have to install dependencies first using apt-get, then use a pip install otherwise the normal pip install of scikit-learn won't work properly. See below:

Step 1: Make sure apt-get is updated

sudo apt-get update
Step 2: Install dependencies

sudo apt-get install build-essential python-dev python-setuptools python-numpy python-scipy libatlas-dev libatlas3gf-base
Step 3: pip install Scikit Learn

pip install --user --install-option="--prefix=" -U scikit-learn

**Comment by waitwathuh** [comment]
Everything is working now. Thank you very much for your help.
