### ISSUE TITLE
Getting error when trying to build a model

### ISSUE THREAD

**Issue by ZeroCool940711** [alfredfrancis/ai-chatbot-framework#36]
I was fallowing this [video ](https://www.youtube.com/watch?v=S1Fj7WinaBA)which is the one on the repo description and got this error when building a model:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Alejandro/Desktop/ai-chatbot-framework-master/app/core/controllers.py", line 16, in buildModel
    IntentClassifier().train()
  File "/mnt/c/Users/Alejandro/Desktop/ai-chatbot-framework-master/app/core/intentClassifier.py", line 40, in train
    outpath=self.PATH, verbose=False)
  File "/mnt/c/Users/Alejandro/Desktop/ai-chatbot-framework-master/app/core/sentenceClassifer.py", line 37, in train
    model = build(X, y)
  File "/mnt/c/Users/Alejandro/Desktop/ai-chatbot-framework-master/app/core/sentenceClassifer.py", line 30, in build
    model.fit(X, y)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/pipeline.py", line 165, in fit
    self.steps[-1][-1].fit(Xt, y, **fit_params)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/multiclass.py", line 278, in fit
    Y = Y.tocsc()
AttributeError: 'numpy.ndarray' object has no attribute 'tocsc'`

Note: I get that error when running the code using python3 but if I run it using python2.7 I get another error saying that flask_cors do not exist even thought I installed the module, or I think I did, maybe im installing the wrong module? if so, then I do not understand why on python3 it recognize the module but not on python2.7 .

Hope you can help me fix this error and looking forward to use your code as it looks interesting.

**Comment by lesyk** [comment]
Why you don't use Docker setup?

**Comment by alfredfrancis** [comment]
@ZeroCool940711 Current version doesn't support python 3. If you use python 2.7 with requirments.txt. everything should work fine.

**Comment by MaterialImplication** [comment]
It seems that scipy 0.17.1 is the problem. I can't install either. I am using python 2.7.

`Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\john\\appdata\\local\\temp\\pip-rfcxxo-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\john\appdata\local\temp\pip-m0ajsn-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\john\appdata\local\temp\pip-rfcxxo-build\`

send help.

**Comment by alfredfrancis** [comment]
Closing the issue for now. Reopen if the issue still exists.

**Comment by MaterialImplication** [comment]
i get this after running run.py
`127.0.0.1 - - [08/Nov/2017 13:45:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2017 13:45:57] "POST /api/v1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/johndoe/Desktop/ai-chatbot-framework/app/endpoint/controllers.py", line 79, in api
    resultJson["intent"]["name"] = story.storyName
AttributeError: 'NoneType' object has no attribute 'storyName'
127.0.0.1 - - [08/Nov/2017 13:46:02] "GET /stories/home HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2017 13:46:02] "GET /stories/ HTTP/1.1" 200 -
127.0.0.1 - - [08/Nov/2017 13:46:06] "POST /core/buildModel/5a0065f603204a0452b928b8 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/johndoe/Desktop/ai-chatbot-framework/app/core/controllers.py", line 16, in buildModel
    IntentClassifier().train()
  File "/Users/johndoe/Desktop/ai-chatbot-framework/app/core/intentClassifier.py", line 40, in train
    outpath=self.PATH, verbose=False)
  File "/Users/johndoe/Desktop/ai-chatbot-framework/app/core/sentenceClassifer.py", line 37, in train
    model = build(X, y)
  File "/Users/johndoe/Desktop/ai-chatbot-framework/app/core/sentenceClassifer.py", line 30, in build
    model.fit(X, y)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/pipeline.py", line 165, in fit
    self.steps[-1][-1].fit(Xt, y, **fit_params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/multiclass.py", line 278, in fit
    Y = Y.tocsc()
AttributeError: 'numpy.ndarray' object has no attribute 'tocsc'`

**Comment by alfredfrancis** [comment]
Did you restore the DB ? How many stories you have? and how much training data per story ?

**Comment by MaterialImplication** [comment]
thank you it worked in my macbook but it didn't for windows. i thought that the restor syntax is for docker only so i didnt restore.

For my windows pc, scipy 0.17.1 won't install but 1.0.0 can. :(
do you have any idea how to fix this error? :)

`Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\john\\appdata\\local\\temp\\pip-build-_ntvkp\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\john\appdata\local\temp\pip-l_nw1f-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\john\appdata\local\temp\pip-build-_ntvkp\scipy\`

thank you! :D

**Comment by lesyk** [comment]
@alfredfrancis close this. @ZeroCool940711 read README.md and follow steps.
