### ISSUE TITLE
Build Model

### ISSUE THREAD

**Issue by alaa069** [alfredfrancis/ai-chatbot-framework#6]
Hello everyone,

When I build model, I get this error log.

Can explain me this problem ?

thank you.

> 127.0.0.1 - - [25/May/2017 14:00:15] "POST /core/buildModel/5926d4a97e058fb3aaf36e36 HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/core/controllers.py", line 15, in buildModel
>     IntentClassifier().train()
>   File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/core/intentClassifier.py", line 39, in train
>     outpath=self.PATH, verbose=False)
>   File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/core/sentenceClassifer.py", line 35, in train
>     model= build(X, y)
>   File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/core/sentenceClassifer.py", line 28, in build
>     model.fit(X, y)
>   File "/usr/local/lib/python2.7/site-packages/sklearn/pipeline.py", line 165, in fit
>     self.steps[-1][-1].fit(Xt, y, **fit_params)
>   File "/usr/local/lib/python2.7/site-packages/sklearn/multiclass.py", line 278, in fit
>     Y = Y.tocsc()
> AttributeError: 'numpy.ndarray' object has no attribute 'tocsc'

**Comment by alfredfrancis** [comment]
Make sure you ran setup.py & you have minimum of two models build with at least 2 sample inputs

**Comment by alaa069** [comment]
Always the same problem.


`127.0.0.1 - - [30/May/2017 10:45:42] "GET /train/5926d4a97e058fb3aaf36e36 HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:45:42] "GET /static/train/js/train.js HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:45:42] "GET /static/commons/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:47:46] "POST /core/posTagAndLabel HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:47:48] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:47:48] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:47:54] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:47:54] "POST /core/sentenceTokenize HTTP/1.1" 200 -
[['book', 'NN', 'O'], ['me', 'PRP', 'O'], ['a', 'DT', 'O'], ['crab', 'NN', 'O'], ['from', 'IN', 'O'], ['aaa', 'NN', 'B-from'], ['to', 'TO', 'O'], ['bbbbb', 'VB', 'B-destination']]
127.0.0.1 - - [30/May/2017 10:48:01] "POST /train/insertLabeledSentence HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:48:31] "POST /core/posTagAndLabel HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:48:32] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:48:32] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:48:37] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:48:37] "POST /core/sentenceTokenize HTTP/1.1" 200 -
[['i', 'NN', 'O'], ['want', 'VBP', 'O'], ['a', 'DT', 'O'], ['crab', 'NN', 'O'], ['from', 'IN', 'O'], ['ttt', 'NN', 'B-from'], ['to', 'TO', 'O'], ['uuuuu', 'VB', 'B-destination']]
127.0.0.1 - - [30/May/2017 10:48:42] "POST /train/insertLabeledSentence HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:49:11] "POST /core/posTagAndLabel HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:49:12] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:49:12] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:49:17] "POST /core/sentenceTokenize HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:49:17] "POST /core/sentenceTokenize HTTP/1.1" 200 -
[['cam', 'NN', 'O'], ['from', 'IN', 'O'], ['oooooooo', 'NN', 'B-from'], ['to', 'TO', 'O'], ['sss', 'VB', 'B-destination']]
127.0.0.1 - - [30/May/2017 10:49:20] "POST /train/insertLabeledSentence HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 10:49:24] "POST /core/buildModel/5926d4a97e058fb3aaf36e36 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/anaconda/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/core/controllers.py", line 15, in buildModel
    IntentClassifier().train()
  File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/core/intentClassifier.py", line 39, in train
    outpath=self.PATH, verbose=False)
  File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/core/sentenceClassifer.py", line 35, in train
    model= build(X, y)
  File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/core/sentenceClassifer.py", line 28, in build
    model.fit(X, y)
  File "/anaconda/lib/python2.7/site-packages/sklearn/pipeline.py", line 165, in fit
    self.steps[-1][-1].fit(Xt, y, **fit_params)
  File "/anaconda/lib/python2.7/site-packages/sklearn/multiclass.py", line 278, in fit
    Y = Y.tocsc()
AttributeError: 'numpy.ndarray' object has no attribute 'tocsc'
`

**Comment by alaa069** [comment]
I had another problem.

```
127.0.0.1 - - [30/May/2017 11:13:43] "GET /stories/home HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 11:13:43] "GET /stories/ HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 11:13:50] "POST /core/buildModel/592d44057e058f1b64c17b0d HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 11:13:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2017 11:13:56] "POST /api/v1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/anaconda/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/upperskills/Documents/python-test/ai-chatbot-framework/app/endpoint/controllers.py", line 78, in api
    resultJson["intent"]["name"] = story.storyName
AttributeError: 'NoneType' object has no attribute 'storyName'

```

**Comment by alaa069** [comment]
Thanks my problem is fixed
