### ISSUE TITLE
While creating stories with Parameter getting error(NameError: global name 'fields' is not defined) 

### ISSUE THREAD

**Issue by yash0924** [alfredfrancis/ai-chatbot-framework#75]
* Restarting with stat
 * Debugger is active!
 * Debugger PIN: 217-332-752
 * Running on http://0.0.0.0:8001/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Mar/2018 14:31:01] "POST /stories/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python27\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\9A\ChatApp\ai-chatbot-framework-master\app\stories\controllers.py", line 56, in createStory
    update_document(parameter, param)
  File "F:\9A\ChatApp\ai-chatbot-framework-master\app\stories\models.py", line 36, in update_document
    ) for key, value in data_dict.items()]
  File "F:\9A\ChatApp\ai-chatbot-framework-master\app\stories\models.py", line 16, in field_value
    fields.ListField,
NameError: global name 'fields' is not defined

**Comment by alfredfrancis** [comment]
This issue has been resolved.
