### ISSUE TITLE
500 Internal Server Error in new API

### ISSUE THREAD

**Issue by AmirHadifar** [alfredfrancis/ai-chatbot-framework#80]
Hi @alfredfrancis,
Thanks for amazing update. I got 500 Internal error in new version when I tried to chat with Bot. I can load and save intents successfully but when I chat with AI-Bot, it didn't return any response. I check log and find-out the issue is related to API-gateway. The error is something like following:

`"POST /gateway/api/v1 HTTP/1.1" 500 141 "http://localhost:8080/agent/default/chat" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "-" `

<img width="803" alt="screen shot 1397-02-11 at 14 20 32" src="https://user-images.githubusercontent.com/7101287/39468949-e11b1d3c-4d4a-11e8-8678-923020b94a31.png">

P.S: I build model with `docker-compose`.

**Comment by alfredfrancis** [comment]
Did you add any intents and build the agent after that?  you need to add one more intent except default intents. Or you can import some intents and training data from importing the following 
 file "examples/restaurant_search.json"

**Comment by PaznerA** [comment]
I'm also getting status 500 :(
docker-ce | docker-compose | no edits - only intents added
Screen:
![iky_chrome_log](https://user-images.githubusercontent.com/7112679/41306033-1a05afcc-6e75-11e8-8006-e8e48b319541.jpg)

**Comment by hadifar** [comment]
I think there is a problem with non-english languages (I checked with Persian and it throws exception).

**Comment by PaznerA** [comment]
So I cannot use strings like "Dům" because of diacritic?

**Comment by John0021** [comment]
Hi @hadifar, @PaznerA, @alfredfrancis  can you guys please help me with fixing 500 internal server error on mac os.
This issue is caused when:
--> i want to save new intent from web app.
--> on every POST and PUT requests, GET works fine.
--> on chat platform.
Build was made through docker-compose following upto the guidelines in Readme.
The below error prompts in every time:
1.)"POST /gateway/api/v1 HTTP/1.1" 500 141 "http://localhost:8080/agent/default/chat" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "-"
2.) Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by corpulent** [comment]
@alfredfrancis where are the error logs.  I am getting 500 errors when trying to chat and create intent/entities.  Fresh setup, followed instructions.

**Comment by rubenvandeven** [comment]
I'm also trying to get it working. I can load the example intents, and train. But the chat then gives a 500.

I'm using docker-compose. @corpulent  It seems the folder is not mounted to docker, but the logs can be shown by using docker-compose: `docker-compose exec iky_backend cat logs/gunicorn-error.log`

Which for me gives:

```
[2018-11-21 17:56:37 +0000] [12] [ERROR] Error handling request //api/v1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/app/endpoint/controllers.py", line 54, in api
    request_json = request.get_json(silent=True)
  File "/usr/local/lib/python2.7/site-packages/flask/wrappers.py", line 150, in get_json
    rv = json.loads(data)
  File "/usr/local/lib/python2.7/site-packages/flask/json/__init__.py", line 199, in loads
    _load_arg_defaults(kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/json/__init__.py", line 117, in _load_arg_defaults
    bp.json_decoder if bp and bp.json_decoder
AttributeError: 'Blueprint' object has no attribute 'json_decoder'

```

@alfredfrancis, The only error I get in the build process is when running `docker-compose exec iky_backend python manage.py init`:
```
WARNING in starspace_intent_classifier [/usr/src/app/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /usr/src/app/model_files doesn't exist
```

**Comment by rubenvandeven** [comment]
So what I can find this seems to be a [flask 0.12.3 specific issue](https://github.com/dpgaspar/Flask-AppBuilder/issues/741), and indeed either downgrading to 12.2 or upgrading to 12.4 changes the error:

```python
```

**Comment by rubenvandeven** [comment]
So what I can find this seems to be a [flask 0.12.3 specific issue](https://github.com/dpgaspar/Flask-AppBuilder/issues/741), and indeed either downgrading to 12.2 or upgrading to 12.4 changes the error:

```python
[2018-11-21 19:14:14 +0000] [12] [ERROR] Error handling request //api/v1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/app/endpoint/controllers.py", line 77, in api
    intent_id, confidence, suggestions = predict(request_json.get("input"))
  File "/usr/src/app/app/endpoint/controllers.py", line 236, in predict
    predicted, intents = sentence_classifier.process(sentence)
  File "/usr/src/app/app/nlu/classifiers/starspace_intent_classifier.py", line 562, in process
    intent_ids, message_sim = self._calculate_message_sim(X, all_Y)
  File "/usr/src/app/app/nlu/classifiers/starspace_intent_classifier.py", line 518, in _calculate_message_sim
    b_in: all_Y})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 76) for Tensor u'a:0', which has shape '(?, 460)'
```

How to reproduce:

- clone master
- docker-compose build
- docker-compose up -d
- docker-compose exec iky_backend python manage.py init
- navigate to http://localhost:8080/agent/default/settings and import examples/restaurant_search.json
- navigate to Intents and Build Agent
- navigate to chat. Instantly yields error in gunicorn-error.log

It seems the model isn't properly trained? Am I forgetting a step?
